### ISSUE TITLE
libdabsdr.so.2 not found after make install - ldconfig needed

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#101]
Seems the `make install` is not working properly, because when I run the app from the build-directory `~/apps/AbracaDABra/build/gui/AbracaDABra` it works fine, while 

```
LANG=C sudo make install
[  5%] Built target AbracaDABra_lrelease
[  7%] Automatic MOC and UIC for target AbracaDABra
[  7%] Built target AbracaDABra_autogen
[100%] Built target AbracaDABra
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/bin/AbracaDABra
-- Up-to-date: /usr/local/share/applications/AbracaDABra.desktop
-- Up-to-date: /usr/local/share/icons/hicolor/512x512/apps/AbracaDABra.png
-- Up-to-date: /usr/local/lib/libdabsdr.so.2.4.0
-- Up-to-date: /usr/local/lib/libdabsdr.so.2
```

will end in

```
$ AbracaDABra 
AbracaDABra: error while loading shared libraries: libdabsdr.so.2: cannot open shared object file: No such file or directory
```

The solution is the following line

```
sudo ldconfig
```

Maybe you can add it to the `README.md`

**Comment by KejPi** [comment]
Some Linux distributions do not even have /usr/local/lib in their ldconf. This is generic linux issue, no application specific, all application that install any library in /usr/local have this problem.

**Comment by andimik** [comment]
Ah, ok

**Comment by KejPi** [comment]
I have added short note about installation prefix, not sure it helps dummy users, advanced users should know already.

**Comment by andimik** [comment]
Better than nothing ...
