### ISSUE TITLE
Freeze when previous loaded raw does not exist any more

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#105]
I'm regularly playing raw files. When I have deleted a previous played raw file or the file/path does not exist, the "open file dialog" will freeze the app. I only can kill the app and delete the ini-file.

**Comment by KejPi** [comment]
Hmm, this is very specific Linux issue, I cannot reproduce it with AppImage but I can reproduce it with "normal" build. It seems to be somehow related to Gnome file dialog that is used under Gnome. I have tried to fix it, please try. 

NOTE: you probably do not have to delete settings completely, just the line with file.

**Comment by andimik** [comment]
Seems this is working now. If it appears again, I'll reopen.
