### ISSUE TITLE
Only one SLS pictures per service stored when filename is the same

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#128]
The function "Data storage" - "Overwrite existing files" does not work as expected.

I have lots of DAB services where the filename stays the same `PAD1_SLS1.JPG` for example.

But as soon a new picture is transmitted (with same file name), it's not saved.

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/2921b8a9-7b0d-456a-a183-f661b32d14de)

When I tick that option, it will be saved, but I'll lose the old one.

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/aa865a5e-63c4-4c08-82c6-9acc8afc5ab0)

# Idea

Check the file size, and as soon as it differs from the previous one, it's a new picture, which shall be stored (maybe with an additional time stamp in the file name).

**Comment by KejPi** [comment]
Well, it works as expected. If the file exist is is either overwritten (if set in settings) or dropped.
If you want to store everything as it is received, you should use transportId in the pattern, for example something like: {transportId}_{contentNameWithExt} 
This shall be unique for a long time.

**Comment by andimik** [comment]
oh, what an interesting undocumented feature! That's exactly what I was looking for. :-)

You have explained me SPI and `{directoryId} | transport ID of directory [only SPI]` is only updated once a day, so I thought I could NOT use the transport ID here.

Maybe you can add this to the readme and add the transport ID to the popup in the tool tip?

**Comment by KejPi** [comment]
Documentation is always painful task. I thought it was clear from the table that transportId applies to any MOT object and to both SLS and SPI application. I will try to improve the description.

**Comment by andimik** [comment]
As you can see, not even I have understood that :-)
