### ISSUE TITLE
German umlauts are displayed incorrectly.

### ISSUE THREAD

**Issue by M4rc-Andre** [KejPi/AbracaDABra#134]
If the song title contains German umlauts, it is not displayed correctly. See picture. 

Wrong: jetzt on air: Die Toten Hosen - WÃ¿nsch dir was
Correct: jetzt on air: Die Toten Hosen - Wünsch dir was

My  system is Linux Mint 21.3 Cinnamon. AbracaDABra build from source.

![image](https://github.com/KejPi/AbracaDABra/assets/16515903/2d1ac928-b213-46a8-93ca-50fe8bbd0907)
![image](https://github.com/KejPi/AbracaDABra/assets/16515903/2f6ac898-91f8-4446-a492-a039eed4a52d)

**Comment by M4rc-Andre** [comment]
However, the umlauts are correct on another channel. Could it be that the radio station is encoding the umlauts incorrectly?

![image](https://github.com/KejPi/AbracaDABra/assets/16515903/ba6d4ba3-0e18-4206-b376-71c12da0feb7)

**Comment by andimik** [comment]
Yes, please inform the radio station. As I am from Austria, you can believe me that all characters are correctly showed by AbracaDABra.

So please close this issue.

**Comment by KejPi** [comment]
I also believe that special characters are handled correctly, we have many special characters in Czech. But if you share a recording, I can inspect it to be sure.
