### ISSUE TITLE
Add EPG button

### ISSUE THREAD

**Issue by KejPi** [KejPi/AbracaDABra#146]
User input: I daily read the EPG (programm guide) und would like a new button for quicker access.

Comment: Options I can see feasible due to space restrictions are:

1) Replace CatSLS button by EPG
2) Add keyboard shortcut for opening EPG
3) Implement a logic to hide buttons under elide (three dots) when they cannot fit
4) Use second line for buttons

**Comment by andimik** [comment]
Just for your information. AbracaDABra also works great with the very detailed Norvegian EPG:

![Image](https://github.com/user-attachments/assets/79565e79-3e7f-4923-8af1-f2f475d14574)

If you wanna play with it: See https://github.com/user-attachments/files/19195238/EPG_NRK1_abracadabra.zip and https://github.com/user-attachments/files/19194889/raw-raw--Tue-Mar-11-18-14-44-2025.zip

**Comment by KejPi** [comment]
Thanks, I like that :-)
FYI: new version is going to show SPI loading progress as you suggested :-)
