### ISSUE TITLE
"Show only current ensemble" feature request

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#149]
The function "Show only current ensemble" has no effect (= will display all muxes), when the channel without a DAB signal.

![grafik](https://github.com/user-attachments/assets/7f2f16b5-cc1e-4e77-9ee8-5f3392eae018)

![grafik](https://github.com/user-attachments/assets/c4a32a19-ab98-4204-8e61-39df740f5118)

So I expect that it will show nothing in such a situation.

**Comment by KejPi** [comment]
In your screenshot - 10C is channel where there is no ensemble in service list or is it a case when no signal is currently available (e.g. disconnected antenna)?

**Comment by andimik** [comment]
In my screenshot 10C is empty.

But thanks for the question, it could have been a disconnected antenna.

**Comment by KejPi** [comment]
I did check this and I can implement what you are asking for but there will be a consequence - the EPG will be empty during tuning until new ensemble ID is received. I am not sure if this is what user wants, what do you think?

**Comment by andimik** [comment]
No, then leave it for now. I will close it.
