### ISSUE TITLE
Application settings/preferences aren't saved when quitting (unless using red dot).

### ISSUE THREAD

**Issue by Tomfr06** [KejPi/AbracaDABra#152]
(v2.5.90 running on macOS Sonoma, tested Intel & Apple Silicon)
When quitting AbracaDABra with anything else than the "red dot" of the window, preferences and settings changed during the session aren't saved.
For example, terminating using 
- AbracaDABra menu > Quit AbracaDABra
- Right click on the Dock icon > Quit
- command+Q keyboard shortcut.
- Activity monitor > X

This is especially annoying/confusing on the first run ever because it won't save the result of the ensemble scan it just did... and will do it again on the next run.

**Comment by KejPi** [comment]
Thanks for reporting, it seems that Cmd+Q or right click on dock do not trigger close event. I have to figure out how to hack it :-(
