### ISSUE TITLE
Archlinux AUR PKGBUILD needs additional dependency

### ISSUE THREAD

**Issue by mastalx** [KejPi/AbracaDABra#165]
For AUR PKGBUILD
https://aur.archlinux.org/packages/abracadabra

to build properly, I had to manually install the following Package:

qt6-location

Since I do not have an Archlinux-Account and you seem to be the same maintainer, I'd like to ask you via this issue-list, to add this package to the dependency list.

Thank you.

**Comment by KejPi** [comment]
Thanks for reporting, it is fixed now.
