### ISSUE TITLE
Timing problem with Ensemble label

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#167]
There is a tiny timing problem, just cosmetic. Tested with 2.6.0 (built from sources).

When you switch to a DAB signal (here 10D) with the drop down and change the channel to an empty one (without any signal, here 10C), it may happen that the Ensemble label (here: "SLO DAB+ R1") remains in the header instead of showing nothing:

![grafik](https://github.com/user-attachments/assets/b61af897-b7a9-4cdf-8361-8cd0aea796d1)

Ensemble information is empty of course:

![grafik](https://github.com/user-attachments/assets/df1f3d0f-54d8-4169-8bf6-1f27c896211d)

**Comment by KejPi** [comment]
I could reproduce the issue but not anymore after [840316a](https://github.com/KejPi/AbracaDABra/commit/840316a8e1a5672812aa4358e62406f7d3beda72) 
Could you please check?

**Comment by andimik** [comment]
Seems this has solved it, thanks!
