### ISSUE TITLE
Feature Request: Minimize Windows

### ISSUE THREAD

**Issue by DigiBC** [KejPi/AbracaDABra#175]
I really like the application and its latest features!   :thumbsup:
More and more useful windows are available and can be opened in parallel. However, at least on Linux, it's difficult to switch between these windows because, except for the main window, the other windows don't have a control button to **minimize the window** - not even the new transmitter map window, which you often drag to a larger size. (A control button to maximize the window would also be helpful here.)

I don't know if these controls are available on other operating systems, but they don't seem to exist on different Linux distributions.

My OS: Linux Mint Debian Edition 6 with Cinnamon Desktop _(with the x86_64.AppImage)_

**Comment by KejPi** [comment]
Good idea and thanks for reminder, I will add it in next version in selected dialogs.
