### ISSUE TITLE
Ensemble label is not updated in service list

### ISSUE THREAD

**Issue by KejPi** [KejPi/AbracaDABra#181]

**Comment by theJazzman42** [comment]
In Linux (Mint 22.0), it took a few minutes. - In Windows 11 it doesn't update.

**Comment by KejPi** [comment]
I am not sure what you meant. This issue refers to the problem that ensemble label stored in service list is not changed when it changes on broadcasting side. This situation is actually very rare but it happened recently in Prague so I was able to detect the issue.
