### ISSUE TITLE
Window resizes to default when changing the audio service

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#23]
Whenever I use the full screen mode or enlarge the Window, it resets to its default window size when changing the audio service.

(I have tested it under Windows 10 21H2)

# Before:
![grafik](https://user-images.githubusercontent.com/24510556/176548302-9bbab386-fd4d-4709-bcf3-f6ad616efbdd.png)

# After
![grafik](https://user-images.githubusercontent.com/24510556/176548408-315fc476-0dde-4365-a3f7-de07eb123d11.png)

**Comment by andimik** [comment]
and same under Ubuntu (built from sources)

# Before

![grafik](https://user-images.githubusercontent.com/24510556/176549200-17ba60e7-e986-4bc7-bfe7-49ea793a0cfa.png)

# After

![grafik](https://user-images.githubusercontent.com/24510556/176549389-c6b13b76-d3b7-4ff5-9c0f-aca211e75d30.png)

**Comment by KejPi** [comment]
Thanks for reporting, I did a brief check and this behavior is already in version 1.0.

**Comment by andimik** [comment]
Yes, now it works.
