### ISSUE TITLE
Expert mode: Change service source icon is shown even for SFNs

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#30]
![grafik](https://user-images.githubusercontent.com/24510556/181806773-ee440ff7-7e28-4a26-870d-4af81d182cb3.png)

The icon **Change service source** should only appear when a mux can be received on different DAB channels, right?

In **Expert mode** it appears even without having duplicates (and has no function of course). Seems the icon is always appearing after the 3rd manual scan (although all of the ensembles are in an SFN). I tried different combinations of all 4 DAB channels I can receive here.

I guess the issue is whenever I do **not** click on a service (see left top corner: **No service**).

This is not related to **Basic mode**, as the first entry will be highlighted immediately after the scan.

**Comment by KejPi** [comment]
What do you mean by 3rd manual scan? Is it that you do the band scan 3 times in row?
Actually first service should start playing after scan for expert mode too.

**Comment by andimik** [comment]
> What do you mean by 3rd manual scan?

The icon **always** appears as soon as there are 3 ensembles in the list. No matter, if they have duplicates.

Not **Band scan**, but selecting the 5A...13F channels manually, see screenshots below.

> Is it that you do the band scan 3 times in row?

No, not really. I select all DAB channels one after the other. In my case I have 5 channels. After the 3rd the icon appears suddenly. Non of the services found have duplicates (not even data services).

# Step 1, empty list

![grafik](https://user-images.githubusercontent.com/24510556/181830773-dd9dcb23-279c-4cf1-ab18-eb4e5ddd5aa4.png)

# Step 2, selecting 10D (1st channel)

![grafik](https://user-images.githubusercontent.com/24510556/181830856-a13e0889-5e65-4ca8-8808-4efc50f3d5b0.png)

# Step 3, selecting 12B (2nd channel)

![grafik](https://user-images.githubusercontent.com/24510556/181830910-96f16230-dcf9-4c82-9253-4bba26e42236.png)

# Step 4, selecting 12C (3rd channel) and icon appears

![grafik](https://user-images.githubusercontent.com/24510556/181830988-af641a72-6cec-4014-ad4b-6ff5ee635812.png)

**Comment by KejPi** [comment]
I can reproduce that :-) thanks for reporting, I will fix it.
