### ISSUE TITLE
RTL TCP gain mode not sent on launch

### ISSUE THREAD

**Issue by orryverducci** [KejPi/AbracaDABra#33]
When the application is setup to use a RTL TCP input device with software gain control it doesn't send the manual gain mode command to the server when the application is launched.

As such if the server is in automatic gain mode it will remain in automatic gain mode when the app expects it to be in manual mode.

It does send the correct commands on launch for the other two gain modes, and it does send the manual gain command when gain control is toggled to another setting and then back to software.

**Comment by KejPi** [comment]
Why do you think it is not sent? I cannot confirm this issue.

**Comment by KejPi** [comment]
Fixed, closing the issue.
