### ISSUE TITLE
"Tuner Gain" issue

### ISSUE THREAD

**Issue by gvanem** [KejPi/AbracaDABra#34]
When running the official 1.2 version under a debugger (cdb.exe), I note a lot of these `qDebug()` messages:
```
[unknown:0] - RTLSDR: Failed to set tuner gain
[unknown:0] - RTLSDR: Failed to set tuner gain
...
```

Now I've built it myself using `clang-cl.exe` (x64) and see no such traces. Linked as a console program:
![AbracaDABra-gv-trace](https://user-images.githubusercontent.com/945271/185580617-e93ac3c5-078e-4513-80f7-688098fd25e9.png)

AFAICS an issue with the `librtlsdr` that is bundled with this release. Where is it from?

*PS*. In my build, I use this [RTLSDR](https://github.com/old-dab/rtlsdr) library using *WinUSB* directly. No libusb involved.

**Comment by KejPi** [comment]
RTLK-SDR comes form here https://github.com/osmocom/rtl-sdr.git
I have built all my libs in MingGW64 (including also libusb-1.0.25). All was built with gcc. I use the app under Windows most of the time and never saw any problem with gain settings using RTL-SDR dongle v3. I have not seen any problem with Nooelec with E4k tuner either, but I use this dongle under Mac.

**Comment by gvanem** [comment]
Not a big deal. Probably some issue with libusb (?). Works like a charm with WinUSB though.
