### ISSUE TITLE
Airspy support

### ISSUE THREAD

**Issue by KejPi** [KejPi/AbracaDABra#4]
Add support for Airspy devices.

**Comment by andimik** [comment]
Thanks to b7d559db664ee1 now the Airspy (mini) is supported.

```
$ ./gui/AbracaDABra
[...]
RTLSDR: No devices found
void MainWindow::changeInputDevice(const InputDeviceId&) 5
AIRSPY: Tuner Sensitivity gain set to 11
AIRSPY: Tuner VGA gain set to 6
virtual void AirspyInput::tune(uint32_t) 215072
void AirspyInput::run()
AIRSPY: Tuner VGA gain set to 6
	Service: Slo 2 Val 202 SID = 0xE49202, SCIdS = 0
```

![image](https://user-images.githubusercontent.com/24510556/181635090-e9a0953e-2820-4756-9e14-93e266a5b0f0.png)

![image](https://user-images.githubusercontent.com/24510556/181635405-5bf0a1a8-a214-49b3-982d-0aee4e7df2e5.png)

Note, that there is always a crash `Segmentation fault (core dumped)` when you want to stop the rawfile recording (I guess at `AirspyInput::stopDumpToFile()`)

Here is a backtrace log of **gdb**

[gdb_bt_airspy_stoprecording.txt](https://github.com/KejPi/AbracaDABra/files/9214188/gdb_bt_airspy_stoprecording.txt)

**Comment by KejPi** [comment]
Implementation is still not completed, there is only basic functionality at the moment, bugs and performance issues are expected. By the way, raw file is dumped in float format for Airspy at the moment, I will probably change that to int16 to reduce file size.

**Comment by KejPi** [comment]
Airspy Mini support implemented, not tested with any other Airspy device, but it will work only with devices supporting 4096kHz sampling rate. CPU load is about 3x more than average load when using RTL-SDR due to filtering and other processing done in Airspy driver.
