### ISSUE TITLE
oldest compatible MacOS ?

### ISSUE THREAD

**Issue by Observerist** [KejPi/AbracaDABra#49]
---- fixes of MacOS DMG generation (support for older version of MacOS, package signature) ----

That's what it says in the description of v1.99.4.
High Sierra aka 10.13 is not compatible. 
Is the next in line, Mojave 10.14 OK ?
What is the oldest I could use ?

**Comment by KejPi** [comment]
Catalina (10.15) is the oldest supported version. Mojave (10.14) could be supported if someone would be willing to test it, High Sierra is not possible because this version is not supported by Qt6.
Do you have Mojave (10.14) on your Mac and can you test the application?

**Comment by KejPi** [comment]
Mojave will be supported in next pre-release 1.99.5
