### ISSUE TITLE
File format to be taken from xml header

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#50]
https://github.com/KejPi/AbracaDABra/blob/cf7282408606f9186fa53da852e03ef135fba727/gui/setupdialog.cpp#L904

Do we really need these line(s)? If no, delete them. 

If yes, we could now read the file format from the xml header, if applicable. Currently, the console output is depending on the file extension (`*.u8`, `*.s16`)

**Comment by KejPi** [comment]
There is plenty of useless messages I have added for debug purposes. Most of them could be probably removed. It probably worries only Linux users, others do not see them. I will clean it up when I have some time. Currently I am trying to implement support for translations.

**Comment by andimik** [comment]
ok fine :-)

**Comment by KejPi** [comment]
Messages removed, if XML header is detected, then format is taken from header. Still only uint8 or int16 LE supported.
