### ISSUE TITLE
RTLSDR does not work when rtl_tcp was running before

### ISSUE THREAD

**Issue by KejPi** [KejPi/AbracaDABra#62]
This issue happens on Win when rtl_tcp was running and closed. After that AbracaDABra is not able to use RTLSDR stick directly. Re-plugging the USB stick typically helps.

**Comment by KejPi** [comment]
RTLTCP built with libusb seems not to have this issue

**Comment by old-dab** [comment]
I can confirm the issue. This commit solved it: 
https://github.com/old-dab/rtlsdr/commit/3d65372f48545dc5b96a23ad00ee0f66d655704d
It seems that libusb never resets the USB pipe.

**Comment by KejPi** [comment]
Thanks, I will update the driver for next release.
