### ISSUE TITLE
Bandwidth settings in ini file only allows 2.2 or 1.8MHz

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#65]
A user from German "Rundfunkforum" wrote:

> I just made some tests with my RTL-SDR-V3-Stick and found that the Abra bandwidth setting is not correct:
"0" or any other number >1700000 results in a true bandwidth of 2.2 MHz, a number <1700000 gives 1.8 MHz. No other settings seem to be possible.
A scan with 2.2 MHz found 11 ensembles, 1.8 MHz gave 12, and a scan in rtl_tcp mode with 1.5 MHz gave 15!

**Comment by KejPi** [comment]
Settings allows anything, the question is what the driver does with the value. I will use 1530kHz as default in future (when there is 0 in INI). It seems that selectivity is more critical than I thought. Unfortunately I do not have possibility for testing it 🙁
