### ISSUE TITLE
libdabsdr.dll not compatible with Windows 10?

### ISSUE THREAD

**Issue by WIHDIA** [KejPi/AbracaDABra#67]
Hi,

I've just replaced libdabsdr.dll with the new one, published 2 hours ago. AbracaDABra won't start, saying this new dll is not compatible.

73

Herman Wijnants
[My logblog](https://www.wijnants.info/fmdx/)
[BELGIUM editor fmlist.org](https://www.fmlist.org/)

**Comment by KejPi** [comment]
This is strange, it works on my test PC. I removed DLL distributed with 2.0 and copied DLL from GitHub and it works:

![obrazek](https://user-images.githubusercontent.com/6438380/224505366-d86f45a6-937b-48cf-8543-c6b6721ddf4f.png)

Did you copy libdabsdr.dll and not libdabsdr.dll.a? And what Windows explorer shows when you right-click on DLL and display Properties?

![obrazek](https://user-images.githubusercontent.com/6438380/224505654-b328b358-14b8-48ac-870d-7ad5e97c9672.png)

**Comment by WIHDIA** [comment]
Hi,

When running the exe:
![afbeelding](https://user-images.githubusercontent.com/53539654/224506019-6a774e54-bcea-4e3a-9a16-6655c0d40866.png)

I do use libdabsdr.dll Not dll.a.

Properties:

![afbeelding](https://user-images.githubusercontent.com/53539654/224506140-c949f1dd-52eb-404a-8260-1f2d6ae21c9b.png)


73

Herman Wijnants
[My logblog](https://www.wijnants.info/fmdx/)
[BELGIUM editor fmlist.org](https://www.fmlist.org/)

**Comment by KejPi** [comment]
The file seems to be corrupted, even the size is wrong, try downloading it again.

**Comment by WIHDIA** [comment]
Hi,

Properties now (size still 204 kB as at first download):

![afbeelding](https://user-images.githubusercontent.com/53539654/224507469-24c7fb4b-1aab-42dd-a223-109ccf8997cc.png)

BUT exe still not running and giving

![afbeelding](https://user-images.githubusercontent.com/53539654/224507480-c034c117-23b8-4793-b38d-ca4ceafa05b6.png)

Perhaps you could send me the dll?  herman@wijnants.info

73

Herman Wijnants
[My logblog](https://www.wijnants.info/fmdx/)
[BELGIUM editor fmlist.org](https://www.fmlist.org/)

Herman Wijnants
[My logblog](https://www.wijnants.info/fmdx/)
[BELGIUM editor fmlist.org](https://www.fmlist.org/)

**Comment by WIHDIA** [comment]
Hi,

It's fixed! I rightclicked and downloaded the dll as shown here:

![afbeelding](https://user-images.githubusercontent.com/53539654/224507930-d5c98796-1348-4512-bba6-e4f79fc4b261.png)

I just should have opened the link and then downloaded:

![afbeelding](https://user-images.githubusercontent.com/53539654/224508001-274c1d67-3d32-4e3f-a72d-a873d2ee07b1.png)

The wrong download (204 kB) was also called libdabsdr.dll .

A bit confusing not using github very often.
Anyway 5A and 5D work well now.

73

Herman Wijnants
[My logblog](https://www.wijnants.info/fmdx/)
[BELGIUM editor fmlist.org](https://www.fmlist.org/)
