### ISSUE TITLE
Collapsing mux list highlights wrong service

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#77]
[Bildschirmaufzeichnung vom 28.04.2023, 06:29:47.webm](https://user-images.githubusercontent.com/24510556/235055238-d2caf270-c475-4157-af00-d1397a7eefc8.webm)

This is just a cosmetic issue which I could reproduce only sometimes.

In this video I was clicking on the 1st service of each mux. After collapsing the mux list, a wrong service got highlighted on the right, which was never selected before. You still can listen to the service marked on the left of course.

**Comment by KejPi** [comment]
Can it be reproduced just selecting some (maybe first) service in the MUX and then keeping collapsing and uncollapsing the ensemble? Without selecting services from other ensembles before?

**Comment by andimik** [comment]
I'll try at home.

**Comment by andimik** [comment]
I found the root cause (drag&drop) but had no luck with the parameters in Qt-Designer in `serviceTreeView`

![grafik](https://user-images.githubusercontent.com/24510556/236891979-8d082ca6-8d2b-4778-a026-845aeceffec3.png)

Here I've just held the left mouse button while moving ... (like drag&drop, but this not activated)

![grafik](https://user-images.githubusercontent.com/24510556/236892283-0c277cb7-b4e0-4410-9159-2f135e07d2df.png)

[Bildschirmaufzeichnung vom 08.05.2023, 19:32:44.webm](https://user-images.githubusercontent.com/24510556/236891653-a14bb9a3-10e4-4f8a-a992-03b95408e457.webm)

**Comment by KejPi** [comment]
This is something I can finally reproduce. I agree that it behaves undesired way leading to selection of the service in service list that does not play but can this behavior explain the what you have observed before?

**Comment by andimik** [comment]
I guess it explains it. Because when you collapse the list, you are holding down the button.

**Comment by KejPi** [comment]
OK, it could be. I will try to find a way to fix this behavior.

**Comment by KejPi** [comment]
I have fixed "drag" issue in e7da6213dd28d5e545815ddffb60be3aa36aaa3a Please check, that the original issue is fixed too.

**Comment by KejPi** [comment]
Fixed in f29385e19ace4f4ddbf34cccd3a3131b94790158

**Comment by andimik** [comment]
Yes, looks good!

BTW: This is the updated German text
[AbracaDABra_de.zip](https://github.com/KejPi/AbracaDABra/files/11444383/AbracaDABra_de.zip)

Hint: "Application log" and the three buttons on the bottom cannot be translated at the moment. I tried to `lupdate` but it does not work.
