### ISSUE TITLE
Tooltip with details for slideshow

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#79]
Nearly all technical details have a mouse over with more details (SBR, Audiocodec, SId, EId, and so on), but not so the slide in the SLS area.

`dablin_gtk` from https://github.com/Opendigitalradio/dablin/ does it like that:

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/348ade7d-276b-4280-89b1-07231c508114)

**Comment by KejPi** [comment]
That could be feasible. The tooltip is currently used to show categorised SLS information.

**Comment by andimik** [comment]
Thanks, is working :-)
