### ISSUE TITLE
Audio recording capability

### ISSUE THREAD

**Issue by KejPi** [KejPi/AbracaDABra#91]

**Comment by andimik** [comment]
Tested Recording with DAB+. 

AAC frames are ok.
Path is localized name for Music :-)

Hint: thanks for escaping the annoying `*` character which is found in some service labels in lots of countries ...

`AudioRecorder: Recording file: "/home/andreas/Musik/2023-11-08-230057_E0AC47__ 88.6 _.aac"`

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/6fb97e46-d6b6-4f9d-a69f-dda6b388ba01)

**Comment by KejPi** [comment]
You can change the recording folder in settings. There are actually more difficult characters, I hope I am removing all that may cause problems.

**Comment by andimik** [comment]
> You can change the recording folder in settings. 

I know as I was translating that as well :-)
